apiVersion: v1

kind: PersistentVolume

metadata:

  name: portainer
  namespace: portainer
  labels:

    type: portainer

spec:

  storageClassName: local-storage

  capacity:

    storage: 2Gi

  accessModes:

    - ReadWriteOnce

  hostPath:

    path: "/mnt/pv"
